Repository FerchusGames/hot-potato, pull requests merged in 2025-06, with the labels that each got.

#154 UI Improvements
  Assets/HotPotato/Assets/Materials/TV_Button.mat
  Assets/HotPotato/Assets/Materials/TV_Button.mat.meta
  Assets/HotPotato/Assets/Textures/Logo.meta
  Assets/HotPotato/Assets/Textures/Logo/Hot Potato Logo.png
  Assets/HotPotato/Assets/Textures/Logo/Hot Potato Logo.png.meta
  Assets/HotPotato/Prefabs/Modules/Module Battery.prefab
  Assets/HotPotato/Prefabs/Modules/Module Button.prefab
  Assets/HotPotato/Prefabs/Modules/Module Cable.prefab
  Assets/HotPotato/Prefabs/Modules/Module Fuse.prefab
  Assets/HotPotato/Prefabs/Modules/Module Switch.prefab
  Assets/HotPotato/Prefabs/Modules/Module.prefab
  Assets/HotPotato/Prefabs/UI/ClueField.prefab
  Assets/HotPotato/Scenes/MainGame/MainGame.unity
  Assets/HotPotato/Scenes/MainGame/MainGame/DeadPlayerProfile.asset
  Assets/HotPotato/Scenes/MainGame/MainGame/DeadPlayerProfile.asset.meta
  Assets/HotPotato/Scenes/Menus/Lobby/SteamLobby.unity
  Assets/HotPotato/Scripts/UI/ClueFieldUI.cs
  Assets/HotPotato/Scripts/UI/MatchResultUI.cs
  Assets/HotPotato/Scripts/UI/WinCounterUI.cs
  Assets/HotPotato/Scripts/Visual.meta
  Assets/HotPotato/Scripts/Visual/DeadPostProcessingController.cs
  Assets/HotPotato/Scripts/Visual/DeadPostProcessingController.cs.meta
  Assets/HotPotato/Settings/PC_Renderer.asset
  ProjectSettings/ProjectSettings.asset
Labels: Feature, UI/UX

#155 Cable module integrated and textures changed
  .gitignore
  Assets/HotPotato/Assets/Models/Materials/M_Metal_v5.mat
  Assets/HotPotato/Assets/Models/Modules/Cable.meta
  Assets/HotPotato/Assets/Models/Modules/Cable/SM_Cable.fbx
  Assets/HotPotato/Assets/Models/Modules/Cable/SM_Cable.fbx.meta
  Assets/HotPotato/Prefabs/Arm.prefab
  Assets/HotPotato/Prefabs/Modules/SM_Cable.prefab
  Assets/HotPotato/Prefabs/Modules/SM_Cable.prefab.meta
  Assets/HotPotato/Scenes/TextureTest.unity
  RawContent/Modules/SM_Cable.fbx
Labels: Art, Art Correction

#158 Implemented camera shake when bomb explodes
  Assets/HotPotato/Prefabs/Player.prefab
  Assets/HotPotato/Scenes/MainGame/MainGame.unity
  Assets/HotPotato/Scripts/Bomb/BombExploder.cs
  Assets/HotPotato/Scripts/Bomb/ExplosionScreenShake.cs
  Assets/HotPotato/Scripts/Bomb/ExplosionScreenShake.cs.meta
  Assets/Utilities/EventBus/Events.cs
Labels: Feature

#159 Add more music tracks and sfx
  Assets/HotPotato/Assets/FMOD/EventReferences/SFX/DefuseEventReference.asset
  Assets/HotPotato/Assets/FMOD/EventReferences/SFX/DefuseEventReference.asset.meta
  Assets/HotPotato/Scenes/MainGame/MainGame.unity
  Assets/HotPotato/Scripts/Audio/MusicTrack.cs
  Assets/HotPotato/Scripts/Audio/MusicTrackChanger.cs
  Assets/HotPotato/Scripts/Audio/MusicTrackChanger.cs.meta
  Assets/HotPotato/Scripts/Bomb/BombExploder.cs
  FMOD/HotPotato/.cache/buildrecords/Desktop/Master.br
  FMOD/HotPotato/.cache/buildrecords/Desktop/SFX.br
  FMOD/HotPotato/.cache/fsbcache/Desktop/2B5BEB7F.fobj
  FMOD/HotPotato/.cache/fsbcache/Desktop/68CB989E.fobj
  FMOD/HotPotato/.cache/{ce3576d0-2f34-47da-87fd-90ddaa4022ca}.pdc
  FMOD/HotPotato/.cache/{e3196d91-82af-4371-993b-0cbefd8676cb}.pdc
  FMOD/HotPotato/Assets/Potato-Bomb-Track-3.mp3
  FMOD/HotPotato/Assets/points_ticker_bonus_no_score_01.wav
  FMOD/HotPotato/Build/Desktop/Master.strings.bank
  FMOD/HotPotato/Build/Desktop/SFX.bank
  FMOD/HotPotato/Metadata/AudioFile/{ce3576d0-2f34-47da-87fd-90ddaa4022ca}.xml
  FMOD/HotPotato/Metadata/AudioFile/{e3196d91-82af-4371-993b-0cbefd8676cb}.xml
  FMOD/HotPotato/Metadata/Event/{554b2e9b-447d-4f44-a3a9-4e1125e81799}.xml
  FMOD/HotPotato/Metadata/Event/{641dd2f4-01a4-41c2-85f8-83ee0f5ca3fa}.xml
  FMOD/HotPotato/Metadata/Event/{adeb5629-17cf-4014-abea-f08159d53493}.xml
  FMOD/HotPotato/Metadata/Event/{b021109e-fd2c-4dcd-b219-3233caf22eba}.xml
  FMOD/HotPotato/Metadata/Event/{dd921f2d-e714-43bd-8957-84b023a942c9}.xml
Labels: Audio
